name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' # Older Flutter versions prefer Java 11

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        # The --no-sound-null-safety flag is the secret sauce here
        run: flutter build apk --debug --no-sound-null-safety
